from __future__ import annotations

from typing import Any


FORMAL_REASON_CODES = frozenset(
    {
        "SOURCE_INVALID",
        "SOURCE_READ_FAILED",
        "SOURCE_HASH_MISMATCH",
        "PDF_ENCRYPTED",
        "RUNTIME_INVALID",
        "RUNTIME_BUSY",
        "RESOURCE_LIMIT_EXCEEDED",
        "PROCESS_TIMEOUT",
        "PROCESS_FAILED",
        "OCR_OUTPUT_INVALID",
        "EVIDENCE_GROUNDING_INVALID",
        "PAGE_CONTENT_UNUSABLE",
        "MODEL_OUTPUT_INVALID",
        "CACHE_RECOVERED",
        "STORAGE_WRITE_FAILED",
        "ARTIFACT_COLLISION",
        "ARTIFACT_INVALID",
        "CONTENT_REVIEW_REQUIRED",
        "PAGE_CONTENT_EXCLUDED",
        "NO_FORMAL_CONCEPT",
        "KNOWLEDGE_MAP_REVIEW_REQUIRED",
        "FORMAL_CONCEPT_REVIEW_REQUIRED",
        "RESOURCE_SPLIT_REVIEW_REQUIRED",
        "RELATION_REVIEW_REQUIRED",
        "RELATION_PAIR_CEILING_EXCEEDED",
        "RELATION_VERIFIER_UNAVAILABLE",
        "RELATION_VERIFIER_DEPENDENCY_MISSING",
        "RELATION_VERIFIER_CUDA_UNAVAILABLE",
        "RELATION_VERIFIER_MODEL_LOAD_FAILED",
        "RELATION_VERIFIER_TIMEOUT",
        "RELATION_VERIFIER_RESPONSE_INVALID",
        "PREREQUISITE_CYCLE",
        "INTERNAL_FAILURE",
    }
)

_SOURCE_INVALID_REASONS = {
    "MEDIA_TYPE_INVALID",
    "PDF_INVALID",
    "PAGE_SELECTION_INVALID",
}
_RESOURCE_LIMIT_REASONS = {"PROTOCOL_LIMIT_EXCEEDED", "MODEL_INPUT_TOO_LARGE"}
_PROCESS_FAILED_REASONS = {
    "CHILD_EXITED",
    "CHILD_RESPONSE_INVALID",
    "CONCEPT_API_RESPONSE_INVALID",
    "CONCEPT_API_UNAVAILABLE",
    "MODEL_OOM",
    "MODEL_GENERATION_FAILED",
}
_EVIDENCE_GROUNDING_REASONS = {
    "OCR_LOCATOR_INVALID",
    "INVALID_EVIDENCE_REFERENCES",
    "DUPLICATE_EVIDENCE_REFERENCE",
    "UNKNOWN_EVIDENCE_ID",
}
_PAGE_CONTENT_UNUSABLE_REASONS = {"NO_USABLE_EVIDENCE", "NO_USABLE_CONCEPT"}
_MODEL_OUTPUT_INVALID_REASONS = {
    "MODEL_OUTPUT_TOO_LARGE",
    "MODEL_OUTPUT_INVALID_JSON",
    "MODEL_OUTPUT_TRUNCATED",
    "CANDIDATE_SCHEMA_INVALID",
    "INVALID_CONCEPT_COUNT",
    "INVALID_TEXT_FIELD",
    "INVALID_KEY_POINTS",
}
_STORAGE_WRITE_REASONS = {
    "CACHE_WRITE_FAILED",
    "FINAL_OUTPUT_WRITE_FAILED",
    "PRODUCER_BUNDLE_WRITE_FAILED",
}
_CONTENT_REVIEW_REASONS = {
    "PAGE_CONTENT_REVIEW_REQUIRED",
    "SEMANTIC_REVIEW_REQUIRED",
    "KNOWLEDGE_MAP_REVIEW_REQUIRED",
}
_DETAILED_REASON_CODES = FORMAL_REASON_CODES.union(
    _SOURCE_INVALID_REASONS,
    _RESOURCE_LIMIT_REASONS,
    _PROCESS_FAILED_REASONS,
    _EVIDENCE_GROUNDING_REASONS,
    _PAGE_CONTENT_UNUSABLE_REASONS,
    _MODEL_OUTPUT_INVALID_REASONS,
    _STORAGE_WRITE_REASONS,
    _CONTENT_REVIEW_REASONS,
    {
        "RUNTIME_BINDING_INVALID",
        "CHILD_TIMEOUT",
        "CONCEPT_API_CONFIG_INVALID",
        "CONCEPT_API_TIMEOUT",
        "CACHE_INVALID",
        "PRODUCER_BUNDLE_INVALID",
    },
)


def formal_reason_code(reason: str) -> str:
    if reason in FORMAL_REASON_CODES:
        return reason
    elif reason in _SOURCE_INVALID_REASONS:
        return "SOURCE_INVALID"
    elif reason in {"RUNTIME_BINDING_INVALID", "CONCEPT_API_CONFIG_INVALID"}:
        return "RUNTIME_INVALID"
    elif reason in _RESOURCE_LIMIT_REASONS:
        return "RESOURCE_LIMIT_EXCEEDED"
    elif reason in {"CHILD_TIMEOUT", "CONCEPT_API_TIMEOUT"}:
        return "PROCESS_TIMEOUT"
    elif reason in _PROCESS_FAILED_REASONS:
        return "PROCESS_FAILED"
    elif reason in _EVIDENCE_GROUNDING_REASONS:
        return "EVIDENCE_GROUNDING_INVALID"
    elif reason in _PAGE_CONTENT_UNUSABLE_REASONS:
        return "PAGE_CONTENT_UNUSABLE"
    elif reason in _MODEL_OUTPUT_INVALID_REASONS:
        return "MODEL_OUTPUT_INVALID"
    elif reason == "CACHE_INVALID":
        return "CACHE_RECOVERED"
    elif reason in _STORAGE_WRITE_REASONS:
        return "STORAGE_WRITE_FAILED"
    elif reason == "PRODUCER_BUNDLE_INVALID":
        return "ARTIFACT_INVALID"
    elif reason in _CONTENT_REVIEW_REASONS:
        return "CONTENT_REVIEW_REQUIRED"
    else:
        return "INTERNAL_FAILURE"


def formal_reason_codes(reasons: list[str]) -> list[str]:
    return sorted({formal_reason_code(reason) for reason in reasons})


def reason_codes_are_valid(value: Any, *, formal: bool) -> bool:
    allowed = FORMAL_REASON_CODES if formal else _DETAILED_REASON_CODES
    return (
        isinstance(value, list)
        and bool(value)
        and all(isinstance(reason, str) and reason in allowed for reason in value)
        and len(value) == len(set(value))
    )
