import os

JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", "dev-change-me")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
MIN_PASSWORD_LENGTH = 8
VERIFICATION_CODE_LENGTH = 6
VERIFICATION_CODE_EXPIRE_MINUTES = 10
PBKDF2_ITERATIONS = 100_000
